---
title: "Chapter 4"
author: "R Pienaar"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf_document: default
---

Load packages

```{r}


library(tidyverse)
library(camtrapR)
library(exiftoolr)
library(unmarked)
library(ggplot2)


Sys.which("exiftool.exe") ### Where is exiftool?
exiftoolPath("C:/Users/ryanp/Documents/Dissertation/Raw data/Nebo Fire/Camera Base 1.7/Fixes/EXIFTool/exiftoolgui/exiftool.exe")

```



Input data
```{r}

rt = read.csv("C:/Users/ryanp/Documents/Dissertation/Chapter4_Camera traps/Camelot Exports/Record Tables/Record_table_mainpulated.csv")
head(rt)

ctt = read.csv("C:/Users/ryanp/Documents/Dissertation/Chapter4_Camera traps/Camelot Exports/Record Tables/Final_camtrap_table.csv")

#df <- df[c(1,4,6,7,8, 15,16)]

camop <- cameraOperation(CTtable = ctt,
                         stationCol = "Station",
                         sessionCol = "Session",
                         setupCol = "Setup_date",
                         retrievalCol = "Retrieval_date",
                         hasProblems = FALSE,             #The cameras were out the whole time, we don't know when the problems happened so I'm just keeping it as no problems
                         dateFormat = "mdy")



```


View data

```{r}

rt <- subset(rt, Species != "Unknown bird")      #remove birds and rabbits
rt <- subset(rt, Species != "Unknown lagomorph")

count_sp <- as.data.frame(table(rt$Species))  # show number of each species
count_sp
names(count_sp) <- c("Species", "N_Obs")

```

```{r}

sp_station <- table(rt$Species,rt$Station)
head(sp_station)


```



Detection History

```{r}

deerdh <- detectionHistory( recordTable = rt,
                            camOp = camop,
                            species = "Odocoileus hemionus",
                            stationCol = "Station",
                            speciesCol = "Species",
                            recordDateTimeCol = "Date",
                            recordDateTimeFormat = "mdy",
                            occasionLength = 30,
                            scaleEffort = FALSE,
                            timeZone = "MST",
                            day1 = "survey",
                            unmarkedMultFrameInput = TRUE)

#deerdh$detection_history

```

Occupancy analysis

```{r}

library(unmarked)
deeref <- deerdh$effort
deerdh <- deerdh$detection_history


Forest <- as.data.frame(substr(rownames(deerdh),5,5))
Fire <- as.data.frame(substr(rownames(deerdh),7,7))

covs <- cbind(Forest, Fire)
colnames(covs) <- c("Forest", "Fire")

deerocc <- unmarkedFrameOccu(y = deerdh, siteCovs = covs)

summary(deerocc)
#deerocc

```

Create Models (Single season)

```{r}



# Null deer model with constant detection and constant occupancy
d.1.1 <- occu(~1~1, data =  deerocc)  #### detection first, then occupancy
d.1.1

d.1.1.psi <- backTransform(d.1.1, type = "state") #Occupancy
d.1.1.psi

d.1.1.p <- backTransform(d.1.1, type = "det") #Detection
d.1.1.p

d.1.1.psi.ci <- confint(d.1.1.psi)
d.1.1.p.ci <- confint(d.1.1.p)

###Constant detection
d.1.FoFi <- occu(~1 ~ Forest + Fire, data = deerocc)
d.1.FoFi

d.1.Fo <- occu(~1 ~ Forest, data = deerocc)
d.1.Fi <- occu(~1 ~ Fire, data = deerocc)


#Constant occupancy
d.FoFi.1 <- occu(~Forest + Fire ~1, data = deerocc)
d.FoFi.1

d.Fo.1 <- occu(~ Forest ~1, data = deerocc)
d.Fi.1 <- occu(~ Fire ~1, data = deerocc)

# Full model
d.FoFi.FoFi <- occu(~Forest + Fire ~Forest+Fire, data = deerocc)

```

Model Selection with constant occupancy to evaluate detection

```{r}

d.const.occ <- fitList(d.FoFi.1,d.Fo.1, d.Fi.1, d.1.1)
modSel(d.const.occ)

d.FoFi.1
newdata <- expand.grid(Forest = levels(deerocc@siteCovs$Forest), 
                       Fire = levels(deerocc@siteCovs$Fire))

det.mod.pred <- predict(d.FoFi.1, type = "det", newdata = newdata, append = TRUE)
det.mod.pred

```

Full Model Selection

```{r}

d.full.occ <- fitList(d.FoFi.1,d.Fo.1, d.Fi.1, d.1.1, d.1.Fi,d.1.Fo, d.1.FoFi, d.FoFi.FoFi)
modSel(d.full.occ)

d.FoFi.1

full.mod.pred <- predict(d.FoFi.1, type = "det", newdata = newdata, append = TRUE)
full.mod.pred

```



Create models (multiseason)

```{r}

#deer1 <- colext(~1 ~1 ~1 ~1, data = deerocc)

```

Different site years occupancy analysis       

```{r}

year.sites <- ctt
year.sites$Station_Session <- paste(ctt$Station, ctt$Session +1, sep = "_")

for (i in year.sites) {
  year.sites$Session <- 1
}

ys.camop <- cameraOperation(CTtable = year.sites,
                            stationCol = "Station_Session",
                            sessionCol = "Session",
                            setupCol = "Setup_date",
                            retrievalCol = "Retrieval_date",
                            hasProblems = FALSE,
                            dateFormat = "mdy")

ys.rt <- rt

ys.rt$Station_Y <- paste(rt$Station, rt$YearsPostfire, sep = "_")

ys.rt <- subset(ys.rt, Species != "Unknown bird")      #remove birds and rabbits
ys.rt <- subset(ys.rt, Species != "Unknown lagomorph")

ys.count_sp <- as.data.frame(table(ys.rt$Species))  # show number of each species
ys.count_sp
names(ys.count_sp) <- c("Species", "N_Obs")

ys.sp_station <- table(ys.rt$Species, ys.rt$Station)
head(ys.sp_station)

ys.deerdh <- detectionHistory( recordTable = ys.rt,
                            camOp = ys.camop,
                            species = "Odocoileus hemionus",
                            stationCol = "Station_Y",
                            speciesCol = "Species",
                            recordDateTimeCol = "Date",
                            recordDateTimeFormat = "mdy",
                            occasionLength = 30,
                            scaleEffort = FALSE,
                            timeZone = "MST",
                            day1 = "survey",
                            unmarkedMultFrameInput = TRUE)

ys.deeref <- ys.deerdh$effort
ys.deerdh <- ys.deerdh$detection_history


ys.Forest <- as.data.frame(substr(rownames(ys.deerdh),5,5))
ys.Fire <- as.data.frame(substr(rownames(ys.deerdh),7,7))
Years_PostFire <- as.data.frame(substr(rownames(ys.deerdh),11,11))

ys.covs <- cbind(ys.Forest, ys.Fire, Years_PostFire)
colnames(ys.covs) <- c("Forest", "Fire", "Years_PostFire")

ys.deerocc <- unmarkedFrameOccu(y = ys.deerdh, siteCovs = ys.covs)

summary(ys.deerocc)


# Null deer model with constant detection and constant occupancy
ys.d.1.1 <- occu(~1~1, data =  ys.deerocc)  #### detection first, then occupancy


ys.d.1.1.psi <- backTransform(ys.d.1.1, type = "state") #Occupancy


ys.d.1.1.p <- backTransform(ys.d.1.1, type = "det") #Detection


ys.d.1.1.psi.ci <- confint(ys.d.1.1.psi)
ys.d.1.1.p.ci <- confint(ys.d.1.1.p)

###Constant detection
ys.d.1.FoFiYf <- occu(~1 ~ Forest + Fire + Years_PostFire , data = ys.deerocc)


ys.d.1.FoFi <- occu(~1 ~ Forest + Fire , data = ys.deerocc)
ys.d.1.FoYf <- occu(~1 ~ Forest + Years_PostFire, data = ys.deerocc)
ys.d.1.FiYF <- occu(~1 ~ Fire + Years_PostFire, data = ys.deerocc)

ys.d.1.Yf <- occu(~1 ~ Years_PostFire, data = ys.deerocc)
ys.d.1.Fo <- occu(~1 ~ Forest, data = ys.deerocc)
ys.d.1.Fi <- occu(~1 ~ Fire, data = ys.deerocc)


#Constant occupancy
ys.d.FoFiYf.1 <- occu(~Forest + Fire + Years_PostFire ~1, data = ys.deerocc)

ys.d.FoFi.1 <- occu(~Forest + Fire ~1, data = ys.deerocc)
ys.d.FoYf.1 <- occu(~Forest + Years_PostFire ~1, data = ys.deerocc)
ys.d.FiYf.1 <- occu(~Fire + Years_PostFire ~1, data = ys.deerocc)

ys.d.Fo.1 <- occu(~ Forest ~1, data = ys.deerocc)
ys.d.Fi.1 <- occu(~ Fire ~1, data = ys.deerocc)
ys.d.Yf.1 <- occu(~ Years_PostFire ~1, data = ys.deerocc)

# Full model
ys.d.FoFiYf.FoFiYf <- occu(~Forest + Fire ~Forest+Fire + Years_PostFire, data = ys.deerocc)

ys.d.full.occ <- fitList(ys.d.1.1, ys.d.1.Fi, ys.d.1.FiYF, ys.d.1.Fo,
                         ys.d.1.FoFi, ys.d.1.FoFiYf, ys.d.1.FoYf, ys.d.Yf.1, ys.d.Fi.1, ys.d.Fo.1,
                         ys.d.FoFi.1, ys.d.FoFiYf.1, ys.d.FiYf.1, ys.d.FoYf.1, ys.d.FoFiYf.FoFiYf)

modSel(ys.d.full.occ)

ys.d.FoFiYf.1
pred.data <- expand.grid(Forest = levels(ys.deerocc@siteCovs$Forest), 
                       Fire = levels(ys.deerocc@siteCovs$Fire),
                       Years_PostFire = levels(ys.deerocc@siteCovs$Years_PostFire))

ys.full.mod.pred <- predict(ys.d.FoFiYf.1, type = "det", newdata = pred.data, append = TRUE)
ys.full.mod.pred

ggplot(data = ys.full.mod.pred, aes(Fire, Predicted, fill = Forest))+
  geom_boxplot()

```


